name: 'Run graphql-schema-linter with reviewdog'
description: '🐶 Run graphql-schema-lisnter with reviewdog on pull requests to improve code review experience.'
author: 'Attsun1031'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for <linter-name> ###
  graphql_schema_linter_version:
    description: 'Version of graphql-schema-linter'
    default: 'latest'
  graphql_schema_linter_flags:
    description: 'Additional graphql-schema-linter-flags'
    default: ''
env:
  REVIEWDOG_VERSION: v0.15.0
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: ${{ env.REVIEWDOG_VERSION }}
    - run: ${GITHUB_ACTION_PATH}/script.sh
      shell: sh
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_GRAPHQL_SCHEMA_LINTER_VERSION: ${{ inputs.graphql_schema_linter_version }}
        INPUT_GRAPHQL_SCHEMA_LINTER_FLAGS: ${{ inputs.graphql_schema_linter_flags }}
branding:
  icon: 'check'
  color: 'blue'
