name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / graphql-schema-linter (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          workdir: ./testdata/

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / graphql-schema-linter (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          reviewdog_flags: "-filter-mode=nofilter -fail-on-error"
          workdir: ./testdata/
          graphql_schema_linter_flags: "test.graphql"

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / graphql-schema-linter (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          reviewdog_flags: -filter-mode=file -fail-on-error
          workdir: ./testdata/
